name: Auto Release

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build CHANGELOG
        run: echo ${{ github.sha }} > CHANGELOG.txt

      - name: Show CHANGELOG
        run: cat CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.txt
          files: |
            release-upload/needUpload.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
