name: Auto Release

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload release
        uses: yakuhzi/action-release@v1
        with:
          file: release-upload/needUpload.js
          changelog: release-upload/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

