name: Logs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  logs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: log github
        run: echo ${{ JSON.stringify(github) }}

