name: Node Test CI
on:
  # run on push events to master
  push:
    branches:
      - master

  # run on pull_request events that target the master branch
  pull_request:
    branches:
      - master

  # run every day of the week from Monday - Friday at 02:00
  schedule:
    - cron: 0 2 * * 1-5

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [latest]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: yarn install
      - run: npm test

