name: Node Test CI
on:
  # run on push events to master
  push:
    branches:
      - master
      - main

  # run on pull_request events that target the master branch
  pull_request:
    branches:
      - master
      - main

  # run every day of the week from Monday - Saturday at 02:00
  schedule:
    - cron: 0 2 * * 1-6

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [ '16', '18' ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test

