name: Set environment variables

on:
  push:

jobs:
  set:
    name: set
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "action_state=1" >> $GITHUB_ENV
          echo "action_state_0=0" >> $GITHUB_ENV
      - name: Use the value directly
        run: |
          echo "${{ env.action_state }}"
          echo "${{ env.action_state_0 }}"

  use:
    name: use
    runs-on: ubuntu-latest
    needs: [set]
    steps:
      - name: Use the value in past job
        run: |
          echo "${{ env.action_state }}"
          echo "${{ env.action_state_0 }}"

