name: Set variables

on:
  push:

jobs:
  set:
    name: set
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "action_state=1" >> $GITHUB_ENV
          echo "action_state_0=0" >> $GITHUB_ENV

      - name: Set output variables
        id: output-variables
        run: |
          echo "state=1" >> $GITHUB_OUTPUT
          echo "state0=0" >> $GITHUB_OUTPUT

      - name: Use the value directly
        run: |
          echo "${{ env.action_state }}"
          echo "${{ env.action_state_0 }}"
          echo "${{ steps.output-variables.outputs.state }}"
          echo "${{ steps.output-variables.outputs.state0 }}"

  save_local_state:
    name: save_local_state
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Save local state
        run: |
          echo 1 > ./state

      - uses: actions/upload-artifact@v3
        with:
          name: state
          path: /

  use:
    name: use
    runs-on: ubuntu-latest
    needs: [ set, save_local_state ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use the value in past job(Failure)
        run: |
          echo "${{ env.action_state }}"
          echo "${{ env.action_state_0 }}"
          echo "${{ steps.output-variables.outputs.state }}"
          echo "${{ steps.output-variables.outputs.state0 }}"

      - name: Use local state
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const state = fs.readFileSync('./state');
            console.log(state);
