name: Test on workflow_run

on:
  workflow_run:
    workflows: [Set variables]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo Test on workflow_run

      - name: Use the value in past workflow(Failure)
        run: |
          echo "${{ env.action_state }}"
          echo "${{ env.action_state_0 }}"

  use_local_state:
    name: use_local_state
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);
            const allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            console.log(allArtifacts);

            const matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "state"
            })[0];
            console.log(allArtifacts);

            const download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            console.log(download);

            const fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/state.zip`, Buffer.from(download.data));

      - name: Unzip artifact
        run: unzip state.zip

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const state = Number(fs.readFileSync('./state'));
            console.log(state);

