name: Test Branch Action

on:
  push:
    branches:
      - master
      - main

jobs:
  logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push updates to test branch
        run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/test-branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: delete test branch
        run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git -d test-branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
